#ifndef UCIE_CHIPLET_RVMODEL_MACROS_H
#define UCIE_CHIPLET_RVMODEL_MACROS_H
#define RVMODEL_DATA_SECTION
#define RVMODEL_IO_WRITE_STR(_R1, _R2, _R3, _STR_PTR)
/* The firmware integration top implements this verification-only result mailbox. */
#define RVMODEL_HALT_PASS  li t0, 0x000001e0; li t1, 1; sw t1, 0(t0); 1: j 1b;
#define RVMODEL_HALT_FAIL  li t0, 0x000001e0; li t1, 2; sw t1, 0(t0); 1: j 1b;
#define RVMODEL_MTIME_ADDRESS 0x000001a0
#define RVMODEL_MTIMECMP_ADDRESS 0x000001a8
#define RVMODEL_ACCESS_FAULT_ADDRESS 0x00010000
#define RVMODEL_TIMER_INT_SOON_DELAY 200
#define RVMODEL_INTERRUPT_LATENCY 16
#define RVMODEL_SET_MEXT_INT(_R1, _R2)
#define RVMODEL_CLR_MEXT_INT(_R1, _R2)
#define RVMODEL_SET_MSW_INT(_R1, _R2)
#define RVMODEL_CLR_MSW_INT(_R1, _R2)
#define RVMODEL_SET_SEXT_INT(_R1, _R2)
#define RVMODEL_CLR_SEXT_INT(_R1, _R2)
#define RVMODEL_SET_SSW_INT(_R1, _R2)
#define RVMODEL_CLR_SSW_INT(_R1, _R2)
#endif
